version: "3.7"

services:
    flask-app:
        build:
            context: ./flask/
        image: flask:latest
        container_name: sample-flask-login-google
        environment:
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        restart: always
        expose:
            - 5000
        ports:
            - 5000:5000
        networks:
            - sample-flask-login-google
        command: python3 /app/app.py 5000

networks:
  sample-flask-login-google:
    name: sample-flask-login-google
    driver: bridge
