version: "3.7"

services:
    flask-app:
        build:
            args:
                DEBUGGING: "true"
        container_name: flask-app
        environment:
            - FLASK_APP=app/server:create_app
            - FLASK_ENV=development
            - FLASK_DEBUG=1
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        ports:
            - 6678:6678
        volumes:
            - ./flask/app:/app
        command: python3 -m debugpy --listen 0.0.0.0:6678 -m flask run -h 0.0.0.0 -p 5000

networks:
    sample-flask-login-google:
    name: sample-flask-login-google
    driver: bridge
